site_name: 土木在线标准
use_directory_urls: false
theme:
  name: material
  features:
    - navigation.tabs
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - 首页: 
    - index.md
  - 钢结构设计标准:
    - 钢结构设计标准 GB50017-2017/封面/封面.md
    - 钢结构设计标准 GB50017-2017/前言/前言.md
    - 钢结构设计标准 GB50017-2017/目录/目录.md
    - 钢结构设计标准 GB50017-2017/1 总则/1 总则.md
    - 钢结构设计标准 GB50017-2017/2 术语和符号/2 术语和符号.md
    - 钢结构设计标准 GB50017-2017/3 基本设计规定/3 基本设计规定.md
    - 钢结构设计标准 GB50017-2017/4 材料/4 材料.md
    - 钢结构设计标准 GB50017-2017/5 结构分析与稳定性设计/5 结构分析与稳定性设计.md
    - 钢结构设计标准 GB50017-2017/6 受弯构件/6 受弯构件.md
    - 钢结构设计标准 GB50017-2017/7 轴心受力构件/7 轴心受力构件.md
    - 钢结构设计标准 GB50017-2017/8 拉弯、压弯构件/8 拉弯、压弯构件.md
    - 钢结构设计标准 GB50017-2017/9 加劲钢板剪力墙/9 加劲钢板剪力墙.md
    - 钢结构设计标准 GB50017-2017/10 塑性及弯矩调幅设计/10 塑性及弯矩调幅设计.md
    - 钢结构设计标准 GB50017-2017/11 连接/11 连接.md
    - 钢结构设计标准 GB50017-2017/12 节点/12 节点.md
    - 钢结构设计标准 GB50017-2017/13 钢管连接节点/13 钢管连接节点.md
    - 钢结构设计标准 GB50017-2017/14 钢与混凝土组合梁/14 钢与混凝土组合梁.md
    - 钢结构设计标准 GB50017-2017/15 钢管混凝土柱及节点/15 钢管混凝土柱及节点.md
    - 钢结构设计标准 GB50017-2017/16 疲劳计算及防脆断设计/16 疲劳计算及防脆断设计.md
    - 钢结构设计标准 GB50017-2017/17 钢结构抗震性能化设计/17 钢结构抗震性能化设计.md
    - 钢结构设计标准 GB50017-2017/18 钢结构防护/18 钢结构防护.md
    - 钢结构设计标准 GB50017-2017/附录A 常用建筑结构体系/附录A 常用建筑结构体系.md
    - 钢结构设计标准 GB50017-2017/附录B 结构或构件的变形容许值/附录B 结构或构件的变形容许值.md
    - 钢结构设计标准 GB50017-2017/附录C 梁的整体稳定系数/附录C 梁的整体稳定系数.md
    - 钢结构设计标准 GB50017-2017/附录D 轴心受压构件的稳定系数/附录D 轴心受压构件的稳定系数.md
    - 钢结构设计标准 GB50017-2017/附录 E 柱的计算长度系数/附录 E 柱的计算长度系数.md
    - 钢结构设计标准 GB50017-2017/附录F 加劲钢板剪力墙的弹性屈曲临界应力/附录F 加劲钢板剪力墙的弹性屈曲临界应力.md
    - 钢结构设计标准 GB50017-2017/附录G 桁架节点板在斜腹杆压力作用下的稳定计算/附录G 桁架节点板在斜腹杆压力作用下的稳定计算.md
    - 钢结构设计标准 GB50017-2017/附录H 无加劲钢管直接焊接节点刚度判别/附录H 无加劲钢管直接焊接节点刚度判别.md
    - 钢结构设计标准 GB50017-2017/附录J 钢与混凝土组合梁的疲劳验算/附录J 钢与混凝土组合梁的疲劳验算.md
    - 钢结构设计标准 GB50017-2017/附录K 疲劳计算的构件和连接分类/附录K 疲劳计算的构件和连接分类.md
    - 钢结构设计标准 GB50017-2017/本标准用词说明/本标准用词说明.md
    - 钢结构设计标准 GB50017-2017/引用标准名录/引用标准名录.md
    - 钢结构设计标准 GB50017-2017/条文说明/条文说明.md

