site_name: 土木在线标准
repo_url: https://github.com/youtian95/Books_OCR
repo_name: Github仓库
use_directory_urls: false
theme:
  name: material
  features:
    - navigation.tabs
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/config.js
  - javascripts/formatting.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - 首页: 
    - index.md
  - 钢结构设计标准:
    - 钢结构设计标准 GB50017-2017/封面/封面.md
    - 钢结构设计标准 GB50017-2017/前言/前言.md
    - 钢结构设计标准 GB50017-2017/目录/目录.md
    - 钢结构设计标准 GB50017-2017/1 总则/1 总则.md
    - 钢结构设计标准 GB50017-2017/2 术语和符号/2 术语和符号.md
    - 钢结构设计标准 GB50017-2017/3 基本设计规定/3 基本设计规定.md
    - 钢结构设计标准 GB50017-2017/4 材料/4 材料.md
    - 钢结构设计标准 GB50017-2017/5 结构分析与稳定性设计/5 结构分析与稳定性设计.md
    - 钢结构设计标准 GB50017-2017/6 受弯构件/6 受弯构件.md
    - 钢结构设计标准 GB50017-2017/7 轴心受力构件/7 轴心受力构件.md
    - 钢结构设计标准 GB50017-2017/8 拉弯、压弯构件/8 拉弯、压弯构件.md
    - 钢结构设计标准 GB50017-2017/9 加劲钢板剪力墙/9 加劲钢板剪力墙.md
    - 钢结构设计标准 GB50017-2017/10 塑性及弯矩调幅设计/10 塑性及弯矩调幅设计.md
    - 钢结构设计标准 GB50017-2017/11 连接/11 连接.md
    - 钢结构设计标准 GB50017-2017/12 节点/12 节点.md
    - 钢结构设计标准 GB50017-2017/13 钢管连接节点/13 钢管连接节点.md
    - 钢结构设计标准 GB50017-2017/14 钢与混凝土组合梁/14 钢与混凝土组合梁.md
    - 钢结构设计标准 GB50017-2017/15 钢管混凝土柱及节点/15 钢管混凝土柱及节点.md
    - 钢结构设计标准 GB50017-2017/16 疲劳计算及防脆断设计/16 疲劳计算及防脆断设计.md
    - 钢结构设计标准 GB50017-2017/17 钢结构抗震性能化设计/17 钢结构抗震性能化设计.md
    - 钢结构设计标准 GB50017-2017/18 钢结构防护/18 钢结构防护.md
    - 钢结构设计标准 GB50017-2017/附录A 常用建筑结构体系/附录A 常用建筑结构体系.md
    - 钢结构设计标准 GB50017-2017/附录B 结构或构件的变形容许值/附录B 结构或构件的变形容许值.md
    - 钢结构设计标准 GB50017-2017/附录C 梁的整体稳定系数/附录C 梁的整体稳定系数.md
    - 钢结构设计标准 GB50017-2017/附录D 轴心受压构件的稳定系数/附录D 轴心受压构件的稳定系数.md
    - 钢结构设计标准 GB50017-2017/附录 E 柱的计算长度系数/附录 E 柱的计算长度系数.md
    - 钢结构设计标准 GB50017-2017/附录F 加劲钢板剪力墙的弹性屈曲临界应力/附录F 加劲钢板剪力墙的弹性屈曲临界应力.md
    - 钢结构设计标准 GB50017-2017/附录G 桁架节点板在斜腹杆压力作用下的稳定计算/附录G 桁架节点板在斜腹杆压力作用下的稳定计算.md
    - 钢结构设计标准 GB50017-2017/附录H 无加劲钢管直接焊接节点刚度判别/附录H 无加劲钢管直接焊接节点刚度判别.md
    - 钢结构设计标准 GB50017-2017/附录J 钢与混凝土组合梁的疲劳验算/附录J 钢与混凝土组合梁的疲劳验算.md
    - 钢结构设计标准 GB50017-2017/附录K 疲劳计算的构件和连接分类/附录K 疲劳计算的构件和连接分类.md
    - 钢结构设计标准 GB50017-2017/本标准用词说明/本标准用词说明.md
    - 钢结构设计标准 GB50017-2017/引用标准名录/引用标准名录.md
    - 钢结构设计标准 GB50017-2017/条文说明/条文说明.md

  - 建筑抗震设计规范:
    - 建筑抗震设计规范 GB 50011-2010/封面/封面.md
    - 建筑抗震设计规范 GB 50011-2010/公告/公告.md
    - 建筑抗震设计规范 GB 50011-2010/修订说明/修订说明.md
    - 建筑抗震设计规范 GB 50011-2010/前言/前言.md
    - 建筑抗震设计规范 GB 50011-2010/目次/目次.md
    - 建筑抗震设计规范 GB 50011-2010/Contents/Contents.md
    - 建筑抗震设计规范 GB 50011-2010/1 总则/1 总则.md
    - 建筑抗震设计规范 GB 50011-2010/2 术语和符号/2 术语和符号.md
    - 建筑抗震设计规范 GB 50011-2010/3 基本规定/3 基本规定.md
    - 建筑抗震设计规范 GB 50011-2010/4 场地、地基和基础/4 场地、地基和基础.md
    - 建筑抗震设计规范 GB 50011-2010/5 地震作用和结构抗震验算/5 地震作用和结构抗震验算.md
    - 建筑抗震设计规范 GB 50011-2010/6 多层和高层钢筋混凝土房屋/6 多层和高层钢筋混凝土房屋.md
    - 建筑抗震设计规范 GB 50011-2010/7 多层砌体房屋和底部框架砌体房屋/7 多层砌体房屋和底部框架砌体房屋.md
    - 建筑抗震设计规范 GB 50011-2010/8 多层和高层钢结构房屋/8 多层和高层钢结构房屋.md
    - 建筑抗震设计规范 GB 50011-2010/9 单层工业厂房/9 单层工业厂房.md
    - 建筑抗震设计规范 GB 50011-2010/10 空旷房屋和大跨屋盖建筑/10 空旷房屋和大跨屋盖建筑.md
    - 建筑抗震设计规范 GB 50011-2010/11 士、木、石结构房屋/11 士、木、石结构房屋.md
    - 建筑抗震设计规范 GB 50011-2010/12 隔震和消能减震设计/12 隔震和消能减震设计.md
    - 建筑抗震设计规范 GB 50011-2010/13 非结构构件/13 非结构构件.md
    - 建筑抗震设计规范 GB 50011-2010/14 地下建筑/14 地下建筑.md
    - 建筑抗震设计规范 GB 50011-2010/附录A 我国主要城镇抗震设防烈度、设计基本地震加速度和设计地震分组/附录A 我国主要城镇抗震设防烈度、设计基本地震加速度和设计地震分组.md
    - 建筑抗震设计规范 GB 50011-2010/附录B 高强混凝土结构抗震设计要求/附录B 高强混凝土结构抗震设计要求.md
    - 建筑抗震设计规范 GB 50011-2010/附录C 预应力混凝土结构抗震设计要求/附录C 预应力混凝土结构抗震设计要求.md
    - 建筑抗震设计规范 GB 50011-2010/附录D 框架梁柱节点核芯区截面抗震验算/附录D 框架梁柱节点核芯区截面抗震验算.md
    - 建筑抗震设计规范 GB 50011-2010/附录E 转换层结构的抗震设计要求/附录E 转换层结构的抗震设计要求.md
    - 建筑抗震设计规范 GB 50011-2010/附录F 配筋混凝土小型空心砌块抗震墙房屋抗震设计要求/附录F 配筋混凝土小型空心砌块抗震墙房屋抗震设计要求.md
    - 建筑抗震设计规范 GB 50011-2010/附录G 钢支撑-混凝土框架和钢框架-钢筋混凝土核心筒结构房屋抗震设计要求/附录G 钢支撑-混凝土框架和钢框架-钢筋混凝土核心筒结构房屋抗震设计要求.md
    - 建筑抗震设计规范 GB 50011-2010/附录H 多层工业厂房抗震设计要求/附录H 多层工业厂房抗震设计要求.md
    - 建筑抗震设计规范 GB 50011-2010/附录J 单层厂房横向平面排架地震作用效应调整/附录J 单层厂房横向平面排架地震作用效应调整.md
    - 建筑抗震设计规范 GB 50011-2010/附录K 单层厂房纵向抗震验算/附录K 单层厂房纵向抗震验算.md
    - 建筑抗震设计规范 GB 50011-2010/附录L 隔震设计简化计算和砌体结构隔震措施/附录L 隔震设计简化计算和砌体结构隔震措施.md
    - 建筑抗震设计规范 GB 50011-2010/附录M 实现抗震性能设计目标的参考方法/附录M 实现抗震性能设计目标的参考方法.md
    - 建筑抗震设计规范 GB 50011-2010/本规范用词说明/本规范用词说明.md
    - 建筑抗震设计规范 GB 50011-2010/引用标准名录/引用标准名录.md
    - 建筑抗震设计规范 GB 50011-2010/条文说明/条文说明.md